services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Entity/'

  App\EventListener\ApiExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: __invoke }
